spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/mydb
    username: "sa"
    password: "123"
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: Initial baseline migration
  jpa:
    hibernate:
      ddl-auto: update # Ou outra estratégia de DDL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect