spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seu-banco-de-dados
    username: "sa"
    password: "123"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Ou outra estratégia de DDL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect