version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data # Persiste os dados do banco
    restart: always

volumes:
  postgres_data:
